[global]
use_syslog 0
logging_level 6
ts2phc.nmea_serialport /dev/gnss0
ts2phc.nmea_baudrate 9600
ts2phc.channel 0
ts2phc.extts_polarity rising
ts2phc.pin_index 1
ts2phc.pulsewidth 100000000
leapfile /usr/share/zoneinfo/leap-seconds.list

[ens4f0np0]
ts2phc.extts_polarity rising
